shfmt -i 2 -ci -w .

diff --git a/bin/vssh b/bin/vssh
--- a/bin/vssh
+++ b/bin/vssh
@@ -3,26 +3,26 @@
 set -eu
 
 if [ ! -s ./Vagrantfile ]; then
-    echo 'Error: No Vagrantfile in current directory.'
-    exit 1
+  echo 'Error: No Vagrantfile in current directory.'
+  exit 1
 fi
 
 ssh_config_path=./ssh-config
 hostname=default
 
 if [ ! -s $ssh_config_path ]; then
-    echo "Creating ssh-config file..."
-    vagrant ssh-config > $ssh_config_path
-    echo "Done."
+  echo "Creating ssh-config file..."
+  vagrant ssh-config >$ssh_config_path
+  echo "Done."
 fi
 
 if [ ! $# -eq 0 ]; then
-    hostname=$1
+  hostname=$1
 fi
 
 SSH=ssh
 if [[ "$(command -v kyrat)" ]]; then
-    SSH=kyrat
+  SSH=kyrat
 fi
 
 $SSH -F "$ssh_config_path" "$hostname"
